"""
Data Seeder for Land Acquisition Cases Prototype.
Populates realistic demo cases across High, Medium, and Low risk profiles.
"""

import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from apps.cases.models import LandAcquisitionCase

DEMO_CASES = [
    # --- HIGH RISK CASES ---
    {
        'case_number': 'LA-2026-NH01',
        'project_name': 'Delhi-Mumbai Expressway Package 14B',
        'sector': 'Highways',
        'state': 'Gujarat',
        'district': 'Vadodara',
        'taluk_village': 'Karjan & Shinor Tehsils',
        'total_area_hectares': 142.5,
        'land_type': 'Agricultural',
        'affected_landowners_count': 380,
        'plots_count': 520,
        'current_stage': 'Hearing of Objections (Sec 15)',
        'days_in_current_stage': 210,
        'env_forest_clearance_status': 'Pending',
        'litigation_cases_count': 4,
        'public_objections_count': 14,
        'compensation_disparity_ratio': 0.64,
        'sia_completed': False,
        'rr_plan_approved': False,
        'is_delayed': True,
    },
    {
        'case_number': 'LA-2026-RW02',
        'project_name': 'Western Dedicated Freight Corridor (Surat-Navsari)',
        'sector': 'Railways',
        'state': 'Gujarat',
        'district': 'Navsari',
        'taluk_village': 'Jalalpore Block',
        'total_area_hectares': 88.0,
        'land_type': 'Commercial',
        'affected_landowners_count': 260,
        'plots_count': 310,
        'current_stage': 'Award & Compensation (Sec 23)',
        'days_in_current_stage': 165,
        'env_forest_clearance_status': 'Approved',
        'litigation_cases_count': 5,
        'public_objections_count': 8,
        'compensation_disparity_ratio': 0.72,
        'sia_completed': True,
        'rr_plan_approved': False,
        'is_delayed': True,
    },
    {
        'case_number': 'LA-2026-UR03',
        'project_name': 'Bengaluru Metro Phase 3 Outer Ring Road',
        'sector': 'Urban Infrastructure',
        'state': 'Karnataka',
        'district': 'Bengaluru Urban',
        'taluk_village': 'Hebbal to Sarjapur Corridor',
        'total_area_hectares': 24.5,
        'land_type': 'Residential',
        'affected_landowners_count': 410,
        'plots_count': 490,
        'current_stage': 'Preliminary Notification (Sec 11)',
        'days_in_current_stage': 140,
        'env_forest_clearance_status': 'Approved',
        'litigation_cases_count': 6,
        'public_objections_count': 19,
        'compensation_disparity_ratio': 0.58,
        'sia_completed': False,
        'rr_plan_approved': False,
        'is_delayed': True,
    },
    {
        'case_number': 'LA-2026-IR04',
        'project_name': 'Polavaram Left Main Canal Submergence Zone',
        'sector': 'Irrigation',
        'state': 'Andhra Pradesh',
        'district': 'East Godavari',
        'taluk_village': 'Devipatnam & Rampachodavaram',
        'total_area_hectares': 320.0,
        'land_type': 'Forest',
        'affected_landowners_count': 560,
        'plots_count': 670,
        'current_stage': 'R&R Implementation',
        'days_in_current_stage': 240,
        'env_forest_clearance_status': 'Pending',
        'litigation_cases_count': 3,
        'public_objections_count': 11,
        'compensation_disparity_ratio': 0.70,
        'sia_completed': True,
        'rr_plan_approved': False,
        'is_delayed': True,
    },
    {
        'case_number': 'LA-2026-IN05',
        'project_name': 'Nagpur Multi-modal International Cargo Hub (MIHAN)',
        'sector': 'Industrial',
        'state': 'Maharashtra',
        'district': 'Nagpur',
        'taluk_village': 'Hingna & Dahegaon',
        'total_area_hectares': 175.0,
        'land_type': 'Agricultural',
        'affected_landowners_count': 320,
        'plots_count': 380,
        'current_stage': 'Declaration of Acquisition (Sec 19)',
        'days_in_current_stage': 190,
        'env_forest_clearance_status': 'Rejected',
        'litigation_cases_count': 2,
        'public_objections_count': 9,
        'compensation_disparity_ratio': 0.66,
        'sia_completed': True,
        'rr_plan_approved': False,
        'is_delayed': True,
    },

    # --- MEDIUM RISK CASES ---
    {
        'case_number': 'LA-2026-NH06',
        'project_name': 'Varanasi-Ranchi-Kolkata Expressway Package 5',
        'sector': 'Highways',
        'state': 'Jharkhand',
        'district': 'Bokaro',
        'taluk_village': 'Chas Block',
        'total_area_hectares': 85.0,
        'land_type': 'Agricultural',
        'affected_landowners_count': 190,
        'plots_count': 230,
        'current_stage': 'Hearing of Objections (Sec 15)',
        'days_in_current_stage': 135,
        'env_forest_clearance_status': 'Pending',
        'litigation_cases_count': 1,
        'public_objections_count': 7,
        'compensation_disparity_ratio': 0.82,
        'sia_completed': True,
        'rr_plan_approved': False,
        'is_delayed': False,
    },
    {
        'case_number': 'LA-2026-RW07',
        'project_name': 'Bilaspur-Manali-Leh Railway Strategic Link',
        'sector': 'Railways',
        'state': 'Himachal Pradesh',
        'district': 'Mandi',
        'taluk_village': 'Sundernagar Valley',
        'total_area_hectares': 52.0,
        'land_type': 'Forest',
        'affected_landowners_count': 115,
        'plots_count': 140,
        'current_stage': 'Preliminary Notification (Sec 11)',
        'days_in_current_stage': 110,
        'env_forest_clearance_status': 'Pending',
        'litigation_cases_count': 1,
        'public_objections_count': 5,
        'compensation_disparity_ratio': 0.85,
        'sia_completed': False,
        'rr_plan_approved': True,
        'is_delayed': False,
    },
    {
        'case_number': 'LA-2026-EN08',
        'project_name': 'Khavda Renewable Energy Park Transmission Line',
        'sector': 'Energy',
        'state': 'Gujarat',
        'district': 'Kutch',
        'taluk_village': 'Bhuj Rural',
        'total_area_hectares': 98.0,
        'land_type': 'Agricultural',
        'affected_landowners_count': 160,
        'plots_count': 190,
        'current_stage': 'Award & Compensation (Sec 23)',
        'days_in_current_stage': 125,
        'env_forest_clearance_status': 'Approved',
        'litigation_cases_count': 2,
        'public_objections_count': 6,
        'compensation_disparity_ratio': 0.79,
        'sia_completed': True,
        'rr_plan_approved': False,
        'is_delayed': False,
    },
    {
        'case_number': 'LA-2026-UR09',
        'project_name': 'Pune Ring Road Eastern Alignment',
        'sector': 'Urban Infrastructure',
        'state': 'Maharashtra',
        'district': 'Pune',
        'taluk_village': 'Purandar & Haveli',
        'total_area_hectares': 105.0,
        'land_type': 'Agricultural',
        'affected_landowners_count': 220,
        'plots_count': 270,
        'current_stage': 'Hearing of Objections (Sec 15)',
        'days_in_current_stage': 120,
        'env_forest_clearance_status': 'Approved',
        'litigation_cases_count': 2,
        'public_objections_count': 8,
        'compensation_disparity_ratio': 0.80,
        'sia_completed': True,
        'rr_plan_approved': False,
        'is_delayed': False,
    },

    {
        'case_number': 'LA-2026-IN10',
        'project_name': 'Dholera Special Investment Region (DSIR Phase 2)',
        'sector': 'Industrial',
        'state': 'Gujarat',
        'district': 'Ahmedabad',
        'taluk_village': 'Dholera Sub-District',
        'total_area_hectares': 110.0,
        'land_type': 'Government/Barren',
        'affected_landowners_count': 65,
        'plots_count': 90,
        'current_stage': 'Declaration of Acquisition (Sec 19)',
        'days_in_current_stage': 110,
        'env_forest_clearance_status': 'Approved',
        'litigation_cases_count': 1,
        'public_objections_count': 2,
        'compensation_disparity_ratio': 0.90,
        'sia_completed': True,
        'rr_plan_approved': True,
        'is_delayed': False,
    },

    # --- LOW RISK CASES ---
    {
        'case_number': 'LA-2026-EN11',
        'project_name': 'Ultra Mega Ultra High Voltage Solar Park 1000MW',
        'sector': 'Energy',
        'state': 'Rajasthan',
        'district': 'Bikaner',
        'taluk_village': 'Nokha Tehsil',
        'total_area_hectares': 250.0,
        'land_type': 'Government/Barren',
        'affected_landowners_count': 18,
        'plots_count': 24,
        'current_stage': 'Physical Possession',
        'days_in_current_stage': 25,
        'env_forest_clearance_status': 'Approved',
        'litigation_cases_count': 0,
        'public_objections_count': 0,
        'compensation_disparity_ratio': 1.18,
        'sia_completed': True,
        'rr_plan_approved': True,
        'is_delayed': False,
    },
    {
        'case_number': 'LA-2026-NH12',
        'project_name': 'NH-44 Bypass & Flyover Extension',
        'sector': 'Highways',
        'state': 'Madhya Pradesh',
        'district': 'Seoni',
        'taluk_village': 'Lakhnadon Bypass',
        'total_area_hectares': 18.5,
        'land_type': 'Agricultural',
        'affected_landowners_count': 32,
        'plots_count': 40,
        'current_stage': 'Award & Compensation (Sec 23)',
        'days_in_current_stage': 30,
        'env_forest_clearance_status': 'Approved',
        'litigation_cases_count': 0,
        'public_objections_count': 1,
        'compensation_disparity_ratio': 1.10,
        'sia_completed': True,
        'rr_plan_approved': True,
        'is_delayed': False,
    },
    {
        'case_number': 'LA-2026-RW13',
        'project_name': 'Gorakhpur-Cantt 3rd Line Doubling Railway Project',
        'sector': 'Railways',
        'state': 'Uttar Pradesh',
        'district': 'Gorakhpur',
        'taluk_village': 'Pipraich Block',
        'total_area_hectares': 12.0,
        'land_type': 'Government/Barren',
        'affected_landowners_count': 22,
        'plots_count': 28,
        'current_stage': 'Physical Possession',
        'days_in_current_stage': 20,
        'env_forest_clearance_status': 'Approved',
        'litigation_cases_count': 0,
        'public_objections_count': 0,
        'compensation_disparity_ratio': 1.05,
        'sia_completed': True,
        'rr_plan_approved': True,
        'is_delayed': False,
    },
    {
        'case_number': 'LA-2026-UR14',
        'project_name': 'Indore BRTS Corridor Dedicated Bus Depot',
        'sector': 'Urban Infrastructure',
        'state': 'Madhya Pradesh',
        'district': 'Indore',
        'taluk_village': 'Niranjanpur Industrial Area',
        'total_area_hectares': 8.5,
        'land_type': 'Commercial',
        'affected_landowners_count': 14,
        'plots_count': 16,
        'current_stage': 'Declaration of Acquisition (Sec 19)',
        'days_in_current_stage': 35,
        'env_forest_clearance_status': 'Not Applicable',
        'litigation_cases_count': 0,
        'public_objections_count': 0,
        'compensation_disparity_ratio': 1.12,
        'sia_completed': True,
        'rr_plan_approved': True,
        'is_delayed': False,
    },
    {
        'case_number': 'LA-2026-IR15',
        'project_name': 'Upper Krishna Sub-Canal Distribution Network',
        'sector': 'Irrigation',
        'state': 'Karnataka',
        'district': 'Bagalkot',
        'taluk_village': 'Jamkhandi Tehsil',
        'total_area_hectares': 35.0,
        'land_type': 'Agricultural',
        'affected_landowners_count': 45,
        'plots_count': 60,
        'current_stage': 'Survey & Demarcation',
        'days_in_current_stage': 28,
        'env_forest_clearance_status': 'Approved',
        'litigation_cases_count': 0,
        'public_objections_count': 1,
        'compensation_disparity_ratio': 1.08,
        'sia_completed': True,
        'rr_plan_approved': True,
        'is_delayed': False,
    }
]

def seed_database():
    print("Seeding database with realistic land acquisition cases...")
    created_count = 0
    for data in DEMO_CASES:
        case, created = LandAcquisitionCase.objects.update_or_create(
            case_number=data['case_number'],
            defaults=data
        )
        # Compute AI intelligence for each seeded case
        res = case.run_risk_assessment()
        print(f"[{case.case_number}] {case.project_name} -> Risk Score: {case.risk_score} ({case.risk_level}) | Stage: {case.predicted_delay_stage}")
        created_count += 1

    print(f"\nSuccessfully seeded and AI-assessed {created_count} cases!")

if __name__ == '__main__':
    seed_database()
