# Generated by Django 6.1.1 on 2026-09-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandAcquisitionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=255, verbose_name='Project / Stretch Name')),
                ('sector', models.CharField(choices=[('Highways', 'Highways & Expressways'), ('Railways', 'Railways & Dedicated Freight Corridors'), ('Urban Infrastructure', 'Urban Infrastructure & Metro'), ('Irrigation', 'Irrigation & Water Resources'), ('Energy', 'Energy, Power & Transmission'), ('Industrial', 'Industrial Corridors & SEZ')], default='Highways', max_length=50)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluk_village', models.CharField(max_length=150, verbose_name='Taluk / Village / Tehsil')),
                ('total_area_hectares', models.FloatField(default=10.0, verbose_name='Total Land Area (Hectares)')),
                ('land_type', models.CharField(choices=[('Agricultural', 'Agricultural Land'), ('Forest', 'Forest & Protected Land'), ('Residential', 'Residential / Homestead'), ('Commercial', 'Commercial / Semi-Urban'), ('Government/Barren', 'Government / Barren Land')], default='Agricultural', max_length=50)),
                ('affected_landowners_count', models.PositiveIntegerField(default=25, verbose_name='Affected Landowners')),
                ('plots_count', models.PositiveIntegerField(default=30, verbose_name='Number of Survey Plots / Survey Nos.')),
                ('current_stage', models.CharField(choices=[('Survey & Demarcation', '1. Survey & Demarcation'), ('Preliminary Notification (Sec 11)', '2. Preliminary Notification (Sec 11)'), ('Hearing of Objections (Sec 15)', '3. Hearing of Objections (Sec 15)'), ('Declaration of Acquisition (Sec 19)', '4. Declaration of Acquisition (Sec 19)'), ('Award & Compensation (Sec 23)', '5. Award & Compensation (Sec 23)'), ('R&R Implementation', '6. R&R Implementation'), ('Physical Possession', '7. Physical Possession')], default='Survey & Demarcation', max_length=100)),
                ('days_in_current_stage', models.PositiveIntegerField(default=15, verbose_name='Days in Current Stage')),
                ('env_forest_clearance_status', models.CharField(choices=[('Approved', 'Approved / Secured'), ('Pending', 'Pending Review / Submission'), ('Rejected', 'Rejected / Queries Raised'), ('Not Applicable', 'Not Applicable')], default='Approved', max_length=50, verbose_name='Env / Forest Clearance')),
                ('litigation_cases_count', models.PositiveIntegerField(default=0, verbose_name='Active Court Stays / Litigations')),
                ('public_objections_count', models.PositiveIntegerField(default=0, verbose_name='Public / Gram Sabha Objections')),
                ('compensation_disparity_ratio', models.FloatField(default=1.0, help_text='1.00 = Market parity. Values below 0.85 indicate severe landowner dissatisfaction.', verbose_name='Compensation Ratio (Offered vs Market Rate)')),
                ('sia_completed', models.BooleanField(default=True, verbose_name='Social Impact Assessment (SIA) Completed')),
                ('rr_plan_approved', models.BooleanField(default=True, verbose_name='R&R Scheme Approved under Sec 16')),
                ('is_delayed', models.BooleanField(default=False, verbose_name='Currently Delayed')),
                ('delay_probability', models.FloatField(default=0.0, verbose_name='Delay Probability (%)')),
                ('risk_score', models.PositiveIntegerField(default=0, verbose_name='Risk Score (0-100)')),
                ('risk_level', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], default='Low', max_length=20)),
                ('predicted_delay_stage', models.CharField(blank=True, default='None', max_length=100)),
                ('top_risk_factors', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('warning_severity', models.CharField(choices=[('LOW', 'Low Severity (Normal)'), ('MODERATE', 'Moderate Severity (Attention Required)'), ('HIGH', 'High Severity (Action Required)'), ('CRITICAL', 'Critical Severity (Urgent Escalation)')], default='LOW', max_length=20)),
                ('last_assessed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Land Acquisition Case',
                'verbose_name_plural': 'Land Acquisition Cases',
                'ordering': ['-risk_score', '-updated_at'],
            },
        ),
    ]
